name: Manual Run automatic Maven Release

on: workflow_dispatch

jobs:
  release:
    name: Release to Maven Central
    runs-on: ubuntu-latest
    steps:
      - name: Setup Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: '3.9.8'

      - name: Release
        uses: speter555/gh-action-mvn-release-main@v0.31.0
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        with:
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          ARTIFACT_STORE_SERVER_ID: ''
          SETTINGS_XML_PATH: '.github/.m2/settings.xml'
          GPG_KEY_ID_GITHUB_TECHUSER: '8611CD28F472E00'
          GPG_SIGNING_KEY_GITHUB_TECHUSER: ${{ secrets.GPG_SIGNING_KEY_GITHUB_TECHUSER }}
          SSH_PRIVATE_KEY_GITHUB_TECHUSER: ${{ secrets.SSH_PRIVATE_KEY_GITHUB_TECHUSER }}
          TECH_USER_USERNAME: 'gnodet'
          TECH_USER_EMAIL: 'gnodet@gmail.com'
          JAVA_VERSION: '22'
          JAVA_DISTRIBUTION: 'temurin'
