name: Manual Run automatic Maven Release

on: workflow_dispatch

jobs:
  release:
    name: Release to Maven Central
    runs-on: ubuntu-latest
    steps:
      - name: Import GPG key
        shell: bash
        # GPG private key, which is exported with armor (start with: '-----BEGIN PGP PRIVATE KEY BLOCK-----') and it is encoded with base64, and stored in secrets
        # the private key is decoded with base64 and it is imported
        run: |
          echo "${{ secrets.GPG_SIGNING_KEY_GITHUB_TECHUSER }}" | base64 --decode | gpg --batch --import
          gpg --keyid-format long --with-fingerprint --list-secret-keys

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          # Private SSH key in PEM format (start with: '-----BEGIN RSA PRIVATE KEY-----')
          key: ${{ secrets.SSH_PRIVATE_KEY_GITHUB_TECHUSER }}
          name: id_rsa
          known_hosts: unnecessary

      - name: Release
        uses: speter555/gh-action-mvn-release-main@v0.31.0
        with:
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          ARTIFACT_STORE_SERVER_ID: ''
          SETTINGS_XML_PATH: '.github/.m2/settings.xml'
          GPG_KEY_ID_GITHUB_TECHUSER: '8611CD28F472E00'
          GPG_SIGNING_KEY_GITHUB_TECHUSER: ${{ secrets.GPG_SIGNING_KEY_GITHUB_TECHUSER }}
          SSH_PRIVATE_KEY_GITHUB_TECHUSER: ${{ secrets.SSH_PRIVATE_KEY_GITHUB_TECHUSER }}
          TECH_USER_USERNAME: gnodet
          TECH_USER_EMAIL: gnodet@gmail.com
          JAVA_VERSION: '22'
          JAVA_DISTRIBUTION: 'graalvm'
